<?php $this->template->contentBegin(POS_TOP);?>
<style>
p{
	font-size: 13px!important;
    line-height: 20px;}
</style>
<?php $this->template->contentEnd();  ?> 
<center class="legal">
    <h2>Terms & Conditions of Service</h2>
  </center>
<div class="container">
   <!--<div class="col-sm-4 col-lg-3">
    <div class="legal-sidebar">
      <h3>Legal</h3>
       <ul>
        <li><a href="<?php echo site_url()."pages/returnscancellations";?>">Refund Policy</a></li>
        <li><a href="<?php echo site_url()."pages/privacystatement";?>">Privacy Statement</a></li>
        <li class="active"><a href="<?php echo site_url()."pages/termsconditions";?>">Terms & Conditions of Service</a></li>
        <li><a href="<?php echo site_url()."pages/termsuse";?>">Terms of Use</a></li>
      </ul>
    </div>
  </div>
  -->
  <div class="col-sm-12 padd-0">
    <div class="contact-right-text">
<div class="personal-text-grey-p"> 
      <p>This website is Designed, Developed and Maintained by Teranex Integrated Solutions Private Limited.
	  </p>
	  <p>
These terms and conditions shall be governed by and construed in accordance with the Indian Laws. Any dispute arising under these terms and conditions shall be subject to the jurisdiction of the courts of Pune. 
</p>
	  <p>
The information posted on this website could include hypertext links or pointers to information created and maintained by Teranex Integrated Solutions Private Limited. Company is providing these links and pointers solely for your information and convenience. When you select a link to an outside website, you are leaving the 'Guidelines of the company and are subject to the privacy and security policies of the owners/sponsors of the outside website.
</p>
	  <p>

Please read the following terms and conditions very carefully as your use of service is subject to your acceptance of and compliance with the following Terms & Conditions.
By subscribing to, or using any of the services, you agree that you have read, understood and are bound by the Terms & Conditions, regardless of how you subscribe to or use the services provided by Teranex Integrated Solutions Private Limited If you do not want to be bound by the Terms & Conditions, you must not subscribe to or use the services. These Terms & Conditions and various other policies are binding as per the provisions of the Information Technology (Intermediaries guidelines) Rules, 2011 formulated under the Information Technology Act, 2000.
</p>

GENERAL INTRO-SERVICES
	  <p>
Teranex Integrated Solutions Private Limited is a provider of online market place, where products/items are displayed online by the various registered Sellers for sale and Buyers can purchase the same, subject to the Terms & Conditions contained herein. Use of the website/app is offered, conditioned on acceptance without modification of all the terms, conditions and notices, contained in these Terms & Conditions, as may be posted and amended on the website/app from time to time.
</p>
NOW THE PARTIES HERETO AGREE AS UNDER:
	 

DEFINITIONS:
 <p>
The following words and terms, whenever used in this Agreement, unless repugnant to the meaning or context thereof, shall have the respective meanings set forth below:
</p>
	  <p>

"Business Day" shall mean the day on which the Indian banks are open for business;
</p>
	  <p>

"Customer" means any company or individual using the TERANEX Platform for buying Products;
</p>
	  <p>

"Effective Date" shall mean the date of acceptance of this Agreement;
</p>
	  <p>

"Losses" means all liabilities, obligations, losses, damages, penalties, actions, judgments, suits, proceedings, costs, expenses and disbursements of any kind or nature whatsoever (including all reasonable costs and expenses of attorneys and the defence, appeal and settlement of any and all suits, actions or proceedings instituted or threatened) and all costs of investigation in connection therewith;
</p>
	  <p>

"Products" means the farmer products which are available on the TERANEX Platform;
</p>
	  <p>

"Proprietary Rights" shall include but shall not be limited to software, all business, technical, marketing and financial information and data, resultant data generated by either Party relating to the performance of its obligations under this Agreement, all Customer related data and information, Customer lists, proprietary data and databases, all trade secrets, know how licenses, know how formulae and processes, this Agreement and the Parties rights and obligations hereunder, all information communicated by one Party to the other Party whether before or after the Effective Date regarding the services, and all other intellectual property whether or not marked confidential;
</p>
	  <p>

"Seller" means any company or individual using the TERANEX Platform to sell the Products;
</p>
INTERPRETATION:
	  <p>

Except where the context otherwise requires, the following rules shall apply to the interpretation of this Agreement:<br />
Unless the context requires otherwise, words importing the singular include the plural and vice versa, and pronouns importing a gender include each of the masculine, feminine and neuter genders.<br />
The words "include", "including", "are inclusive of" and similar expressions are not expressions of limitation and shall be construed as if followed by the words "without limitation".<br />
Unless the context otherwise requires, the words "hereof", "hereunder" and "hereto" and words of like import, refer to this Agreement as a whole.
Where any act, matter or thing is required by this Agreement to be performed or carried out on a certain day and that day is not a Business Day, then that act, matter or thing shall be carried out or performed on the following Business Day;<br />
References to "writing" and "written" include any mode of reproducing words in a legible and non-transitory form including electronic mail and facsimile.
</p>
AGREEMENT AND SCHEDULES:
	  <p>


The terms and conditions set forth in this clause and any additional or different terms expressly agreed by the Parties shall constitute the entire Agreement and understanding between the Parties with respect to Agreement and shall cancel and supersede any other prior or contemporaneous discussions, agreements, representations, warranties, and/or other communications between them. Notwithstanding anything to the contrary, both the Parties shall always remain subject to the terms of this Agreement.
</p>
	  <p>

Both Parties agree, understand and acknowledge that TERANEX's role is limited to managing the platform for the display of the Products and other incidental services to facilitate the transactions between Seller and Customer. Accordingly, TERANEX is merely an intermediary as defined under Information Technology Act, 2000 and rules there under and is only an online platform where the Sellers offers its Products for sale. The Agreement for the sale of farmer Products shall be a strictly bipartite contract between Seller and the Customer. At no time shall TERANEX have any obligations or liabilities in respect of such contract nor shall TERANEX hold any rights, title or interest in the sales. TERANEX shall not be responsible for any unsatisfactory, delayed performance of the Seller including delays in delivering the Products or non-availability or cancellation of orders.
</p>
SCOPE OF WORK
	  <p>



Seller shall get itself registered with the TERANEX Platform for the purposes of offering its Products for sale and shall upload continually on an as on basis the comprehensive and up to date information, including descriptions, varieties and types of Products available on the TERANEX Platform. 
</p>
	  <p>

When the Customer purchases a Product from the TERANEX Platform, the said purchase has to be approved by TERANEX. Once the purchase is approved, the Seller shall dispatch the Product to be delivered to the Customer through the courier services engaged for the said purpose within two (2) days (goods being perishable in nature) from the transaction date on the address provided by the Customer.
</p>
	  <p>

The payment for the purchase of the Product can be made either at the time of delivery of the Product to the official of the courier service (Cash on Delivery) or at the time of purchasing the Product on the TERANEX Platform via Payment Gateway.
</p>
	  <p>

All the Payments made to the logistic partner i.e. courier service engaged for delivering the Product shall be deposited in the TERANEX Account and the same shall be transferred to the Seller's account once the invoices have been raised against them.
</p>
	  <p>

The Seller shall raise invoices for the amount equivalent to the sales made through the TERANEX Platform by the end of every week. TERANEX will make the payment to the Seller within 30 days from the receipt of the undisputed invoices.
</p>
ACCOUNT<br />
	  <p>

You (Buyer/Seller) will receive a password and account designation upon completing the website/app's registration process. In consideration of your use of the website/app, you represent that you are of legal age (i.e., no less than 18 years of age), to form a binding contract, and are not a person barred from receiving services by/under the laws as applicable in India. You also agree to provide true, accurate, current and complete information about yourself as prompted by the website/app's registration form. If you provide any information that is untrue, inaccurate, not current or incomplete (or becomes untrue, inaccurate, not current or incomplete), or Teranex Integrated Solutions Private Limited has reasonable grounds to suspect that such information is untrue, inaccurate, not current or incomplete, Teranex Integrated Solutions Private Limited has the right to suspend or terminate your account and refuse any and all current or future use of the website/app (or any portion thereof). If you use the website/app, you are responsible for maintaining the confidentiality of your account and password including cases when it is being used by any of your family members, friends or relatives, whether a minor or an adult. You further agree to accept responsibility for all transactions made from your account and any dispute arising out of any misuse of your account, whether by any family member, friend, relative, any third party or otherwise shall not be entertained by Teranex Integrated Solutions Private Limited Because of this, we strongly recommend that you exit and logout from your account at the end of each session. Teranex Integrated Solutions Private Limited cannot and will not be liable for any loss or damage arising from your failure to comply.
</p>
	  <p>

ADDITION AND APPROVAL OF PRODUCTS<br />
The Seller must be legally able to sell the item(s) you list for sale on our website/app. The Seller must ensure that the listed items do not infringe upon the intellectual property, trade secret or other proprietary rights or rights of publicity or privacy rights of third parties. Listings may only include text descriptions, graphics and pictures that describe your item for sale. All listed items must be listed in an appropriate category on the website/app. All listed items must be kept in stock for successful fulfilment of sales. The listing description of the item must not be misleading and must describe actual condition of the product. If the item description does not match the actual condition of the item, the Seller agrees to refund any amounts that the Seller may have received from the Buyer.
</p>
	  <p>

ORDER PLACEMENT<br />
The Seller and Buyer agree and acknowledge that Teranex Integrated Solutions Private Limited is only a facilitator and is not, and cannot be a party to or control in any manner any transactions on the website/app. Accordingly, the contract of sale of products on the website/app shall be a strictly bipartite contract between the Seller and the Buyer. Teranex Integrated Solutions Private Limited does not at any point of time during any transaction between Buyer and Seller on the website/app come into or take possession of any of the products or services offered by Seller nor does it at any point gain title to or have any rights or claims over the products or services offered by Seller to Buyer. The Acceptance of Seller for the order shall be in accordance with the availability of the items/products and the area they have to be delivered to, as provided by the Buyer.
</p>
DELIVERY<br />
	  <p>

The Buyer will be given various options for delivery of items during the order process. The options available to the Buyer will vary depending on where the Buyer is ordering from. An estimated delivery time is displayed on the order summary page. On placing the order, the buyer will receive an email containing a summary of the order and also the estimated delivery time to the Buyer's location. A pre-approved logistics partner will be assigned for the delivery of the items ordered. Sometimes, delivery may take longer due to unforeseen circumstances. In such cases, Teranex Integrated Solutions Private Limited will proactively reach out to you by e-mail and SMS. However, Teranex Integrated Solutions Private Limited will not be able to compensate for any mental agony caused due to delay in delivery.
</p>
SHIPPING<br />
	  <p>

The price of our merchandise is inclusive of the VAT. The vat charged shall depend upon the destination where the order has to be shipped. The tax rate applied to the order will be the combined tax rate for both state and local tax rates in accordance with the address where the order is being shipped. Teranex Integrated Solutions Private Limited reserves the right to collect taxes for shipping charges wherever applicable.
</p>
RETURNS, REFUNDS AND EXCHANGE<br />
	  <p>

Returns, refunds and exchange are applicable to items sold on Teranex Integrated Solutions Private Limited  In general, an item may be eligible for return, refund or exchange within the applicable return time frame, as specified on the product specification page, if it fulfils one or more of the following conditions: (a) it was delivered in a physically damaged condition, (b)cit was missing parts or accessories, (c)cit was different from what was ordered. All items must be returned in their original condition, with tags intact, manuals, warranty cards, accessories and in the original manufacturer's box/packaging as delivered to you. If the item you wish to exchange doesn't have an exchange option, you'll need to return the original item and place a new order. Items marked as "non-returnable" (mostly perishable items) on the product specification page cannot be returned or exchanged.
</p>
COMMUNICATION<br />
	  <p>

When you visit the website/app or send emails to us, you are communicating with us electronically. You consent to receive communications and newsletters from us electronically. We will communicate with you by email or by posting notices on the website/app. You agree that all agreements, notices, disclosures and other communications that we provide to you electronically satisfy any legal requirement that such communications be in writing.
</p>
LAW AND JURISDICTION<br />
	  <p>

These terms shall be governed by and constructed in accordance with the laws of India without reference to conflict of laws principles and disputes arising in relation hereto shall be subject to the exclusive jurisdiction of the courts at Pune.
</p>
INDEMNIFICATION<br />
	  <p>

Indemnification by Customer<br />
The Customer shall indemnify, defend and hold harmless the Indemnified Parties from any and all claims, damages, liabilities, costs, and expenses (including, but not limited to, reasonable attorneys fees and all related costs and expenses) arising from or relating to:<br />
such Customer's use of Services, including without limitation claims by or on behalf of any Seller;<br />
any Service Contract entered into between such Customer and Seller; or<br />
any breach of their obligations set forth herein.<br /><br />
 
Indemnification by Seller<br />
Each Seller shall indemnify, defend and hold harmless the Indemnified Parties from any and all claims, damages, liabilities, costs, and expenses (including, but not limited to, reasonable attorneys fees and all related costs and expenses) arising from or relating to:<br />
such Seller's provision of Services;<br />
any Service Contract entered into between such Seller and Customer; or <br />
any breach of their obligations set forth herein.<br /><br />

VIOLATION & TERMINATION<br />
Teranex Integrated Solutions Private Limited in its sole discretion and without prior notice reserves the right to terminate the Buyer's or Seller's access to the website/app, and also block future access, if Teranex Integrated Solutions Private Limited determines that the Buyer/Seller has violated the Terms & Conditions or any other policies. Any suspected fraudulent, abusive or illegal activity may be referred to appropriate law enforcement authorities. Following termination, the Buyer/Seller will not be permitted to use the website/app and the company may, in its sole discretion and without giving any advance notice, cancel any outstanding orders for items/products. If the Buyer/Seller or Teranex Integrated Solutions Private Limited terminates the use of any service, the Seller/Buyer shall still be liable to pay for any service that you have already ordered till the time of such termination.<br /><br />
INTELLECTUAL PROPERTY RIGHTS<br />
Each Party shall own all Intellectual Property rights in respect of their respective web sites and other services, including any literature, manuals, reports, or other information or materials in whatever form and on whatever media stored or held, acquired, created, developed, designed or otherwise prepared by the respective Party and any related patents, trademarks, logos and service marks, registered designs, utility models or applications provided by the Party owning the same. No Party may, under any circumstances, seek to register any trademark, business name, business processes, inventions, company name, domain name using or incorporating the Intellectual Property of the other Party and each Party acknowledges that upon expiry or termination of this Agreement, it shall have no right whatsoever in connection with the Intellectual Property of the other Party.<br /><br />

LIMITATION OF LIABILITY<br />

To the greatest extent permissible under law, neither Party shall be liable for any special, indirect, punitive, exemplary, incidental or consequential loss or damage, loss of profits, business, revenue and/or goodwill. Notwithstanding anything to the contrary, the maximum aggregate liability of a Party shall be limited to a certain amount and the same shall be decided as per the business/ services entered between the Parties. (it depends upon the nature of Agreement)<br /><br />

JURISDICTION & GOVERNING LAW<br />

This Agreement and any action, dispute, controversy or claim arising there under and related thereto shall be governed in accordance with the law of India without regard to its conflict of laws provisions. All disputes, differences and/or claims arising out of or relating to or in connection with this Agreement or the breach, termination or validity hereof shall be referred to sole arbitrator, to be appointed by TERANEX. The place of the arbitration shall be Pune, India and shall be subject to the provisions of the arbitration and conciliation Act 1996 as amended from time to time. The award given by the arbitrator shall be final and binding on both the Parties. The language of the arbitration proceedings and award shall be English. Subject to the above, the exclusive jurisdiction in respect of this Agreement shall be the courts of Pune and each of the Parties hereto waives any objection to the jurisdiction in such courts. However, in the event of the actual or threatened infringement, misappropriation or violation of TERANEX Proprietary Rights, TERANEX may, at its discretion institute legal proceedings in any jurisdiction(s) which is/are deemed necessary or advisable.<br /><br />

Other Clauses - <br /><br />

Relationship<br />
The relationship between the Parties is that of independent contractors. Nothing contained in this Agreement shall be construed or deemed to create any association, agency relationship, partnership or joint venture or employer-employee relationship in any manner whatsoever between the Parties. <br /><br />

Modification: <br />
No modification or amendment to this Agreement shall be binding upon Parties unless made in a written instrument which is duly signed by the authorized representatives of the Parties. For the purposes of this Clause, a written instrument shall expressly exclude electronic communications such as email and electronic notices but shall include facsimiles.<br /><br />
Non Waiver: <br />
The failure or delay of either Party to exercise or enforce any right or claim does not constitute a waiver of such right or claim and shall in no way affect that Party's right to later enforce or exercise it, unless such Party issues an express written waiver, signed by a duly authorized representative of each Party.<br /><br />

Severability: <br />
If and to the extent any provision of this Agreement is held illegal, invalid, or unenforceable in whole or in part under applicable law, such provision or such portion thereof shall be ineffective as to the jurisdiction in which it is illegal, invalid, or unenforceable to the extent of its illegality, invalidity, or unenforceability, and shall be deemed modified to the extent necessary to conform to applicable law so as to give the maximum effect to the intent of the Parties. The illegality, invalidity, or unenforceability of such provision in that jurisdiction shall not in any way affect the legality, validity, or enforceability of such provision in any other jurisdiction or of any other provision in any jurisdiction.<br /><br />

Survival: <br />
Any and all obligations under this Agreement which, by their very nature should reasonably survive the termination or expiration of this Agreement, will so survive, including, but not limited to, those arising from the confidentiality, Intellectual Property and indemnity provisions of this Agreement.<br /><br />

Notices:<br />
Any notice to be given by a Party under this Agreement must be in writing in the english language and will be deemed to have been duly given (a) when delivered by hand (with written confirmation of receipt); (b) when sent by facsimile (with written confirmation of receipt), provided that a copy is mailed by registered mail, return receipt requested, or (c) when received by the addressee, if sent by nationally recognized overnight delivery service (receipt requested), in each case to the appropriate addressed set forth in the first paragraph of this Agreement (or to such other addresses as a Party may designate by notice to the other Party).<br /><br />

Headings:  <br />
The headings have been inserted for convenience and reference only and shall not be construed to affect the meaning, construction or effect of this Agreement.<br />

<br>

      </p>
    </div>
  </div>
</div>
</div>
